### ISSUE TITLE
When `use_tilemap_layers`  toggled, properties in "tilelayer" are not imported correctly.

### ISSUE THREAD

**Issue by pcloves** [Kiamo2/YATI#11]
**Describe the bug**
When importing a Tmx file with `use_tilemap_layers`  toggled, The properties in the "tilelayer" of Tiled, such as `y_sort_enabled`, `z_index` ,  which should be belong to the Layer of TileMap, are applied to TileMap by mistake.

**To Reproduce**
1. In Tiled, add an `int` property `z_index`(100) in the layer: `tree`.
2. In Godot, open YATI import window, toggle `Use Tilemap Layers` on
3. Import
4. Open the imported scene. check the `z_index` property of the `TileMap`(not the layer of TileMap), which is set to 100.

**Expected behavior**
The `z_index` property should be set on the `tree`'s layer.

**Screenshots**
<img width="959" alt="image" src="https://github.com/Kiamo2/YATI/assets/4152188/95c901c5-62c6-4f97-a7a6-84142314eb05">
<img width="878" alt="image" src="https://github.com/Kiamo2/YATI/assets/4152188/979b2471-4e69-4ffd-855b-281562b8f63d">

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.2.4
 - Godot Version 4.0.3
 - Tiled Version 1.10.1

**Comment by Kiamo2** [comment]
This raises an interesting question: How to differentiate between the CanvasItem's properties 'z_index' and 'y_sort_enabled' and the same named Layers' properties.
My proposal is to add properties with names 'layer_z_index' and 'layer_y_sort_enabled' in Tiled to clarify that the according Layer properties in Godot and not the Canvas properties are targeted.
This way there would be no uncertainty left which Godot property is to be set.

Would you agree to that proposal?

**Comment by pcloves** [comment]
> This raises an interesting question: How to differentiate between the CanvasItem's property `z_index` and the same named Layers' property.

Based on my limited understanding of Godot and Tiled, It seems that the CanvasItem's property `z_index` should come from the "map Properties" in Tiled, rather than from "Layer Properties". 

That means:
Tiled "map property" -->  TileMap(CanvasItem's) property `z_index` 
Tiled "Layer property" --> TileMap Layer's property `z_index`

If I am correct, there is no need to prefix "layer_" for the property `z_index` because it is possible to set a `z_index` in the "Map Properties" and another `z_index` in the "Layer Properties" without conflicting their names.


I hope I am expressing myself clearly because I am using Google Translator ~_~

**Comment by Kiamo2** [comment]
Unfortunately it's not not as easy as you might think.
A Tiled map is not neccessarily equivalent to a Godot TileMap.
The Tiled map is equivalent to a complete Godot scene which might well be only a simple TileMap (in your case) but in various other cases not.
E.g. if 'use_tilemap_layers' is not set or the Tiled map additionally contains objects the base node in Godot will become a Node2D instead of a (Godot-)TileMap.
Thus Tiled's map properties as having no clear equivalent in Godot are currently not mapped at all.
It's probably possible to account for your case as "special case" and handle it like you proposed, but frankly I don't like special solutions as they are prone to unforeseeable side effects.
The proposal with the 'layer_' prefix would be unambigous and thus clean and additionally quite simple to implement.
Please note that in Godot the z_index property is fully qualified as 'layer_0/z_index' (or 'layer_1/z_index' and so on) which is at least a bit similar to 'layer_z_index'. (You can see that if you hover the mouse over the propery name).

**Comment by pcloves** [comment]
> A Tiled map is not neccessarily equivalent to a Godot TileMap.
The Tiled map is equivalent to a complete Godot scene which might well be only a simple TileMap (in your case) but in various other cases not.

I did some tests, the results are just as you said. 

I still have a question that haven't been clarified yet: When `use_tilemap_layers` is toggled, and there are some layers in Tiled, with each layer has a `z_index` property. Which `z_index` property should TileMap(CanvasItem's)  ues?

 It seems due to the `use_tilemap_layers` option, the Tilemap properties and the layer  properties become complicated and ambiguous. We cannot intuitively determine whether the properties of the Tiled layer are mapped onto the TileMap or the layer of the TileMap.

**Comment by Kiamo2** [comment]
I've thought about all that and slept over it and I think now the best solution would be that if use_tilemap_layers is enabled the z_index property should go to the layer's z_index and if it's not enabled it's going to the canvas item (like now).
Probably the z_index on the canvas is not needed at all, if the TileMap has multiple layers, but I'm not sure.
Additionally to this heueristicaI determination I will add the possibility to be explicit by naming it either 'layer_z_index' or 'canvas_z_index'.
-> A simple 'z_index' without prefix will go either to the canvas item (if 'use_tilemap_layers' is off) or to the layer (if it's on).
If that's not wished it's possible to be explicit.

**Comment by pcloves** [comment]
Ah, this plan looks very sensible to me.

**Comment by Kiamo2** [comment]
Fixed in v1.2.5
