### ISSUE TITLE
How do I access raw tile id data?

### ISSUE THREAD

**Issue by Psygnomi** [Kiamo2/YATI#29]
For a given tile map layer, how do I access the tile value for a particular tile?

**Comment by Kiamo2** [comment]
Access from where, from inside Godot?

**Comment by AnagramImmersive** [comment]
Ah sorry - I should've been more specific! This is a simple collision map - one value for collide, one value for free-to-move.

Access from a C# script. I was hoping to just grab an int array containing the tile values. 

I've since found GetUsedCellsById( ), which might work if I pass in the value for the collide tile, then pass in the coordinates of where I want to move to to see if there's a collide tile at that position int the returned array. Seems a bit long winded compared to a simple array lookup, but if it works, it works! :)

**Comment by Psygnomi** [comment]
Ah sorry - I should've been more specific! This is a simple collision map - one value for collide, one value for free-to-move.

Access from a C# script. I was hoping to just grab an int array containing the tile values.

I've since found GetUsedCellsById( ), which might work if I pass in the value for the collide tile, then pass in the coordinates of where I want to move to to see if there's a collide tile at that position int the returned array. Seems a bit long winded compared to a simple array lookup, but if it works, it works! :)

**Comment by Kiamo2** [comment]
Looking at the [docu for GetUsedCellsById()](https://docs.godotengine.org/en/stable/classes/class_tilemap.html#class-tilemap-method-get-used-cells_by_id) and the parameters the method expects I've some doubts if you really would get useful information for your purposes. I assume the source_id to pass is the atlas source id () not a tile id.
![source_id](https://github.com/Kiamo2/YATI/assets/122157211/85c4872d-5efc-4ef3-98b4-0ecd14a9d7f3)

But I'm not a Godot programming guru and so that's only sort of my "feeling".

Concerning collisions I'd probably try to make use of tile collision rects.
Those are imported to Godot.

**Comment by Psygnomi** [comment]
Your gut feeling was correct :(

However, I've found a solution - a bit hacky, but using GetCellAtlasCoords() I can test against the atlas cell containing the blocking tile, and build a simple map up that way:

```
private byte[,] CollisionMap = new byte[MapWidth, MapHeight];

private void InitCollisionMap()
{
        string mapStr = "";
        
        for (int y = 0; y < MapHeight; y++)
        {
	        for (int x = 0; x < MapWidth; x++)
	        {
		        CollisionMap[x, y] = (byte)((tm.GetCellAtlasCoords(0, new Vector2I(x, y)) == BlockingTile) ? 1 : 0);
		        mapStr += CollisionMap[x, y];
	        }
        
	        mapStr += '\n';
        }
        
        GD.Print( mapStr );
}
```

Thanks for your help :)
