### ISSUE TITLE
Tile Collision Polygons not updating in Godot.

### ISSUE THREAD

**Issue by cachi01** [Kiamo2/YATI#40]
Hello! Sorry, it might not be a bug but I'm not sure if I'm doing something wrong here. 

**Describe the bug**
I try to create collisions in tiled but they won't appear in the tileset setting in Godot. I've managed to create physics layers in the tilemap but when I'm creating the collision shapes inside tiled and save the file, they are not being updated in Godot. 

All other properties update correctly.

**To Reproduce**
Create collision shape for tile in Tiled and add the custom property physics_layer to it. 
Go back to godot
Check the tileset 
the tile does not have the collision polygon set to it.

**Expected behavior**
Collision polygon in Godot should be created and be the same as the one in Tiled

**Desktop:**
 - OS: Windows 10
 - Version: 1.6.3 - GDScript
 - Godot Version: 4.2.1
 - Tiled Version: 1.10.2

**Comment by cachi01** [comment]
Tried changing polygon
Exported tmx with edited polygon and it worked

I tried changing the polygon to another thing now, reexported tmx but this time it simply did not work. Closing and reopening godot does not change this either.

**Comment by cachi01** [comment]
Been playing around with it and noticed Collision Data won't update unless each map is individually re-exported/saved after a tile collision change in the .tsx

Is it possible for the plugin to assign collision data for all tmx using that tileset once the tileset's tsx gets updated?

**Comment by Kiamo2** [comment]
The problem is probably that changes only in a .tsx don't trigger an automatic reimport of .tmx files.
An automatic reimport is only triggered on changes in .tmx files.
Unfortunately we have to live with that somehow.
The import mechanism is built-in Godot, the importer code cannot do much about that.
Additionally the .tsx files don't contain any info in which .tmx they are used so there is no easy other way to circumvent that.

For a single .tmx you can manually force a reimport by switching to the Import tab (left top side) and press Reimport.
(If the Import window is empty you first must reselect the .tmx file in the browser on the left - Godot pecularity).

If you have lots of .tmx all based on the same .tsx a faster workaround could be to close Godot, then delete all .tmx.import files and restart Godot. With missing .impot files a reimport is also forced and Godot writes a new import file.
